#!/usr/bin/env node
// vibe-usage statusline wrapper — generated by Vibe Usage for Windows.
// Do not edit; overwritten on next install/repair.
//
// Claude Code pipes a status payload here on every statusline render. We tee
// the rate_limits slice to ~/.vibe-usage/claude-rate-limits.json (atomic
// write), then re-run the user's ORIGINAL statusline command with identical
// stdin so any existing HUD keeps working untouched.
//
// Node port of the macOS app's bash wrapper (vibe-usage-statusline.sh) —
// Windows has no bash, but Node is always present (the app ships one).
"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawn } = require("child_process");

const VIBE_DIR = path.join(os.homedir(), ".vibe-usage");
const OUT = path.join(VIBE_DIR, "claude-rate-limits.json");
const SIDECAR = path.join(VIBE_DIR, "statusline-original");

let raw = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => (raw += d));
process.stdin.on("end", () => {
  try {
    const o = JSON.parse(raw);
    const rl = o && o.rate_limits;
    if (rl && (rl.five_hour != null || rl.seven_day != null)) {
      const out = {
        five_hour: rl.five_hour ?? null,
        seven_day: rl.seven_day ?? null,
        model_id: (o.model && o.model.id) || null,
        captured_at: Math.floor(Date.now() / 1000),
      };
      try {
        fs.mkdirSync(VIBE_DIR, { recursive: true });
        const tmp = path.join(VIBE_DIR, `.claude-rate-limits.${process.pid}.${Date.now()}`);
        fs.writeFileSync(tmp, JSON.stringify(out));
        try {
          fs.renameSync(tmp, OUT);
        } catch {
          // Extremely defensive: rename-over-existing works on Windows via
          // libuv (MOVEFILE_REPLACE_EXISTING), but never leave temp litter.
          try {
            fs.unlinkSync(tmp);
          } catch {}
        }
      } catch {}
    }
  } catch {}

  // Forward to the user's original statusline command (same stdin), if any.
  let original = null;
  try {
    original = fs.readFileSync(SIDECAR, "utf8").trim();
  } catch {}
  if (original) {
    const child = spawn(original, {
      shell: true,
      stdio: ["pipe", "inherit", "inherit"],
      windowsHide: true,
    });
    child.on("error", () => process.exit(0));
    child.on("exit", (code) => process.exit(code == null ? 0 : code));
    child.stdin.on("error", () => {});
    child.stdin.end(raw);
  } else {
    process.exit(0);
  }
});
